### ISSUE TITLE
Angular 11 

### ISSUE THREAD

**Issue by HashtagAssist** [josealejandro2928/ngp-image-picker#16]
Hey! Im using Angular 11.0.6
when I try to install your libary i get some errors 

@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.
@angular/core/core"' has no exported member 'ɵɵComponentDeclaration'.
@angular/core/core"' has no exported member 'ɵɵInjectorDeclaration'.

Seems to be incompatible with Angular 11.0.6

**Comment by josealejandro2928** [comment]
Bro I just update the library for angular 13, following the rules of the official web site, because a lot of people of the community wanted it.
I did some research and this is an angular compatibility issue between app >=12 and apps<12.
I've just created a new clean project with ng new of version 12 and the package works perfectly.
![Screenshot from 2022-03-25 16-21-48](https://user-images.githubusercontent.com/37028825/160150306-ffc8b9d5-4eb9-4f0e-aea2-f4a00ed9f335.png)

**Comment by HashtagAssist** [comment]
Ah okay. Then I will update my project. I really want to use your lib.. Its fantastic. Thank you for the research!

**Comment by josealejandro2928** [comment]
Thanks, i'm starting to do the implementation of new features like the capability of edit :
-contract level
-brightness
-sepia
etc
And adopt a full component more or less like the instagram
An another think will be the implementation for react.
Tell me your opinion

**Comment by HashtagAssist** [comment]
That would be great 👍
Nice Features.
For our purposes, everything we need is there! Really super project!
A few small style adjustments are necessary to adapt it to our interface, but everyone can do that themselves... so I think a PR is not that useful

If we use it finally in production in our e-commerce dashboard, we would like to spend you a coffee or two ;)
