### ISSUE TITLE
When using routes, edit button will reroute to the root of the app

### ISSUE THREAD

**Issue by douwetiemersma** [josealejandro2928/ngp-image-picker#23]
In my app I'm using routing with @angular/router
the imagePicker is located on path:'edit/:contactId'
When I add an image, and click on the edit button, the link it wil follow is http://localhost:3000/polyfills.js which will send the user to the homapage (path:'') in the app. Is there a way to fix this? This behaviour doesn't happen when clicking any other button

**Comment by douwetiemersma** [comment]
Some extra details: the overlay is loaded, until a Scheduled Macro task sends the browser to the root by executing
sendNative.apply(target, data.args);

**Comment by josealejandro2928** [comment]
I cannot reproduce the problem. This should not happens, because the behavior of the "Edit" button is a boolean state that open and internal components that looks like a full screen modal. I think that there is not relation between the logic of this component and the  Routing mechanism of angular. I you can try to reproduce the problem on stackblitz
this  is the link: [https://stackblitz.com/edit/angular-ivy-otu4f3?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/angular-ivy-otu4f3?file=src%2Fapp%2Fapp.component.ts)

**Comment by josealejandro2928** [comment]
It is checked

**Comment by 5Gears0Chill** [comment]
This is happening to me as well

**Comment by 5Gears0Chill** [comment]
> This is happening to me as well

I actually get a webpack dev server disconnected
